# Boltz2 affinity prediction on CSAR-HIQ_51
name: boltz2_csar_hiq51
standardized_csv: data/Structure_independent/CSAR-HIQ_51_standardized_test.csv
ground_truth_path: data/CSAR-HIQ_51/index.txt
ground_truth_format: csv
path: data/CSAR-HIQ_51
