name: sequence_casp16_l3000_v5_repro
path: data/Structure_independent/L3000_casp16_test.csv
mode: inference
ground_truth_path: data/Structure_independent/L3000_casp16_test.csv
ground_truth_format: csv
series_group: sequence_casp16_v5_repro

task: pdbbind_v5_repro
model_path: forks/LLF/models/pdbbind_v5_repro/best_model_full.pth
max_seq_len: 1200
