name: sequence_casp16_l1000_stage2_finetune
path: data/Structure_independent/L1000_casp16_test.csv
mode: inference
ground_truth_path: data/Structure_independent/L1000_casp16_test.csv
ground_truth_format: csv
series_group: sequence_casp16_stage2_finetune

task: stage2_finetune
model_path: forks/LLF/models/stage2_finetune/best_model_full.pth
max_seq_len: 1500
