name: sequence_kiba
path: data/Structure_independent/KIBA/test_1.csv # Default to fold 1, required by run_benchmark.py
test_file: data/Structure_independent/KIBA/test_1.csv # Redundant but good for clarity
label_column: label
smiles_column: compound_iso_smiles
sequence_column: target_sequence
target_id_column: Target ID
experiment_type: sequence
problem_type: regression
metric_type: correlation
dataset_name: KIBA
